# Add support for reading an external config file
smallrye:
  config:
    locations: "/config/config.yaml"

# Information about the Cognite Data Fusion (CDF) project
cognite:
  # (Optional) CDF deployment target
  host: "https://api.cognitedata.com"

  # CDF project
  project:
  # OpenID Connect client credentials authentication
  clientId:
  # The client secret should be specified via an env. variable COGNITE_CLIENTSECRET
  clientSecret:
  azureADTenantId:

source:
  rawDb: "sap-extract"
  flocTable: "functional-location"
  eqTable: "equipment"
  workCenterTable: "workcenter"

metrics:
  enable: false
  jobName: "http extractor"
  pushGateway:
    url: "http://internal-prometheus-pushgateway.internal-services:9091"