# Add support for reading an external config file
smallrye:
  config:
    locations: "/config/config.yaml"

# Default config
cdf:
  authentication:
    apiKey:
    apiKeyGcp: ""

source:
  rawDb: "sap-extract"
  flocTable: "functional-location"
  eqTable: "equipment"
  workCenterTable: "workcenter"

metrics:
  enable: false
  jobName: "http extractor"
  pushGateway:
    url: "http://internal-prometheus-pushgateway.internal-services:9091"