apiVersion: skaffold/v4beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
    # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: interactive-pnid-batch-job
    context: .
    jib: {}
manifests:
  rawYaml:
    - kubernetes-manifests/interactive-pnid-batch-job.yaml
