apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: notification-pipeline
build:
  artifacts:
  - image: notification-pipeline
    context: .
    jib:
      project: com.cognite:notification-pipeline
  tagPolicy:
    sha256: {}
manifests:
  rawYaml:
    - kubernetes-manifests/notification-pipeline.configmap.yaml
    - kubernetes-manifests/notification-pipeline.cronjob.yaml