# Custom configuration options should be added to this file. It will be mapped into the
# application pod and made available to the container as /config/config.yaml

# Information about the Cognite Data Fusion (CDF) project
cognite:
  # (Optional) CDF deployment target
  #host: "https://api.cognitedata.com"
  host: "https://greenfield.cognitedata.com"
  # CDF project
  project:
  # Api key authentication. You can also specify this entry via an env. variable COGNITE_APIKEY
  apiKey:
  # OpenID Connect client credentials authentication
  clientId:
  # The client secret should be specified via an env. variable COGNITE_CLIENTSECRET
  clientSecret:
  azureADTenantId:
  # (Optional) Authentication scopes
  scopes:
    - "https://api.cognitedata.com/.default"

# State store configuration
stateStore:
#  local:
#    path: "./statestore.json"
#    saveInterval: 30
  raw:
    database: "met-system"
    table: "statestore-cap-extractor"
    saveInterval: 30

# The CDF Raw source configuration
source:
  rawDb: "met"
  rawTable: "met-alerts-rss-items"

# Target data set and extraction pipelines
target:
  rawDb: "met"
  rawTable: "met-alerts-cap-items"
  extractionPipelineExternalId: "ep:met-alerts-cap-extractor"

# Default configuration for metrics.
metrics:
  enable: false
  jobName: "met-alerts-cap-extractor"
  pushGateway:
    url: "http://stable-prometheus-pushgateway.internal-services:9091"