apiVersion: skaffold/v2beta13
kind: Config
build:
  tagPolicy:
    sha256: {}
    # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: europe-west1-docker.pkg.dev/akerbp-eureka-sa-sandbox/containers/raw-to-clean-batch-job
    context: .
    jib: {}
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/raw-clean-batch.job.yaml
