apiVersion: skaffold/v2beta29
kind: Config
build:
  tagPolicy:
    sha256: {}
    # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: raw-to-clean-batch-job
    context: .
    jib: {}
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/raw-clean-batch.job.yaml
