apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: raw-to-clean-batch-job
build:
  local:
    push: false
  tagPolicy:
    sha256: { }
    # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: raw-to-clean-batch-job
    context: .
    jib:
      project: com.cognite:cdf-sdk-java-example-raw-clean-batch
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/raw-clean-batch.deployment.yaml
