apiVersion: batch/v1
kind: Job
metadata:
  name: raw-to-clean-batch-job
spec:
  template:
    spec:
      containers:
      - name: raw-to-clean-batch-job
        image: europe-west1-docker.pkg.dev/akerbp-eureka-sa-sandbox/containers/raw-to-clean-batch-job
        ports:
        - containerPort: 9090
        env:
        - name: RAW_DB
          value: "kjetilh-dev.val-stage1-copy"
        - name: DATASET_EXT_ID
          value: "dataset:kjetilh-dev"
        - name: CDF_API_KEY_SECRET_MANAGER
          value: "919896902461.akerbp-dev-kjetilh"
        # This environment variable enables debugging support for the container.
        # Remove this to disable the debug build.
        #- name: JAVA_TOOL_OPTIONS
        #  value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      restartPolicy: Never
      serviceAccountName: transform-default
