# Custom configuration options should be added to this file. It will be mapped into the
# application pod and made available to the container as /config/config.yaml

# The authentication section
cdf:
  authentication:
    apiKey:
    apiKeyGcp: ""

source:
  rawDb: "sap-extract"
  table: "notification"

# Configuration for metrics.
metrics:
  enable: false
  jobName: "my-raw-to-clean-batch-pipeline"
  pushGateway:
    url: "http://prometheus-pushgateway.victoria-metrics:9091"