apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: workorder-pipeline
build:
  artifacts:
  - image: workorder-pipeline
    context: .
    jib:
      project: com.cognite:workorder-pipeline
  tagPolicy:
    sha256: {}
manifests:
  rawYaml:
    - kubernetes-manifests/workorder-pipeline.configmap.yaml
    - kubernetes-manifests/workorder-pipeline.cronjob.yaml