apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: default
commonLabels:
  app.kubernetes.io/name: raw-to-clean-batch-job
  app: raw-to-clean-batch-job
resources:
  - raw-clean-batch.job.yaml

# The generator will convert the config.yaml file into a K8 config map which can be mapped
# into the container
configMapGenerator:
  - name: raw-to-clean-batch-job-config
    files:
      - config.yaml=config.yaml

generatorOptions:
  disableNameSuffixHash: true