apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: met-alerts-cap-extractor
build:
  local:
    push: false
  artifacts:
  - image: met-alerts-cap-extractor
    context: .
    jib:
      fromImage: "gcr.io/distroless/java17-debian11"
  tagPolicy:
    dateTime:
      format: "20060102T150405"
      timezone: "UTC"
manifests:
  kustomize:
    paths:
      - ./kubernetes-manifests/
