apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-extractor-equipment-config
data:
  config.yaml: |
    # The http source configuration
    source:
      uri: "https://fiori.s5consulting.no//sap/opu/odata/sap/ZODATA_EQUIPMENT_SRV/EquipmentTypeSet?$format=json"
      method: "GET"
      body: ""
      authentication:
        protocol: "basic"
        id: "ext_cognite"
        secret:
        secretGcp: ""

    response:
      format: "json"
      path: "d.results"
      rowKey: ["Mandt", "Equipment"]

    target:
      rawDb: "sap-extract"
      rawTable: "equipment"
      authentication:
        apiKey:
        apiKeyGcp: ""