# Custom configuration options should be added to this file. It will be mapped into the
# application pod and made available to the container as /config/config.yaml

# Information about the Cognite Data Fusion (CDF) project
cognite:
  # (Optional) CDF deployment target
  host: "https://api.cognitedata.com"

  # CDF project
  project:

  # Api key authentication. You can also specify this entry via an env. variable COGNITE_APIKEY
  apiKey:

  # OpenID Connect client credentials authentication
  clientId:
  # The client secret should be specified via an env. variable COGNITE_CLIENTSECRET
  clientSecret:
  azureADTenantId:
  # (Optional) Authentication scopes
  scopes:
    - "https://api.cognitedata.com/.default"

# Source config.
source:
  fileUri: "gs://apache-beam-samples/shakespeare/kinglear.txt"

# Target config
target:
  fileUri: "./fileOut.txt"
  dataSetExternalId:
  extractionPipelineExternalId:

# Configuration for metrics.
metrics:
  enable: false
  jobName: "my-raw-to-clean-batch-pipeline"
  pushGateway:
    url: "http://prometheus-pushgateway.victoria-metrics:9091"