# Custom configuration options should be added to this file. It will be mapped into the
# application pod and made available to the container as /config/config.yaml

# Information about the Cognite Data Fusion (CDF) project
cognite:
  # (Optional) CDF deployment target
  host: "https://greenfield.cognitedata.com"

  # CDF project
  project: "kjetilh-greenfield"
  # OpenID Connect client credentials authentication
  clientId: "632ac8e6-0b02-423e-b2ab-e1da4f2a1724"
  # The client secret should be specified via an env. variable COGNITE_CLIENTSECRET
  clientSecret:
  azureADTenantId: "445b2055-5094-4672-9cab-d37920dac4e2"

# Source raw db and table to read source data from.
source:
  rawDb: "met"
  table: "met-alerts-cap-items"

# (Optional) Target data set and extraction pipelines
target:
  dataSetExternalId: "ds:src002:met"
  extractionPipelineExternalId: "ep:met-alerts-pipeline"

# Configuration for metrics.
metrics:
  enable: false
  jobName: "met-alerts-cap-pipeline"
  pushGateway:
    url: "http://prometheus-pushgateway.victoria-metrics:9091"