# Custom configuration options should be added to this file. It will be mapped into the
# application pod and made available to the container as /config/config.yaml

# Information about the Cognite Data Fusion (CDF) project
cognite:
  # (Optional) CDF deployment target
  host: "https://api.cognitedata.com"

  # CDF project
  project:
  # OpenID Connect client credentials authentication
  clientId:
  # The client secret should be specified via an env. variable COGNITE_CLIENTSECRET
  clientSecret:
  azureADTenantId:

# State store configuration
stateStore:
  #  local:
  #    path: "./statestore.json"
  #    saveInterval: 30
  raw:
    database: "met-system"
    table: "statestore-cap-pipeline"
    saveInterval: 30

# Source raw db and table to read source data from.
source:
  rawDb: "met"
  table: "met-alerts-cap-items"

# (Optional) Target data set and extraction pipelines
target:
  dataSetExternalId: "ds:src002:met"
  extractionPipelineExternalId: "ep:met-alerts-pipeline"

# Configuration for metrics.
metrics:
  enable: false
  jobName: "met-alerts-cap-pipeline"
  pushGateway:
    url: "http://prometheus-pushgateway.victoria-metrics:9091"