apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: default
commonLabels:
  app.kubernetes.io/name: met-alerts-cap-pipeline
  app: met-alerts-cap-pipeline
resources:
  - met-alerts-cap-pipeline.job.yaml

# The generator will convert the config.yaml file into a K8 config map which can be mapped
# into the container
configMapGenerator:
  - name: met-alerts-cap-pipeline-config
    files:
      - config.yaml=config.yaml

generatorOptions:
  disableNameSuffixHash: true