apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: asset-hierarchy-pipeline
build:
  artifacts:
  - image: asset-hierarchy-pipeline
    context: .
    jib:
      project: com.cognite:asset-hierarchy-pipeline
  tagPolicy:
    sha256: {}
manifests:
  rawYaml:
    - kubernetes-manifests/asset-hierarchy-pipeline.configmap.yaml
    - kubernetes-manifests/asset-hierarchy-pipeline.cronjob.yaml