apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: met-alerts-cap-pipeline-beam
build:
  local:
    push: false
  artifacts:
  - image: met-alerts-cap-pipeline-beam
    context: .
    jib:
      fromImage: "gcr.io/distroless/java17-debian11"
  tagPolicy:
    dateTime:
      format: "20060102T150405"
      timezone: "UTC"
deploy:
  kustomize:
    paths:
      - ./kubernetes-manifests/
profiles:
  - name: ci
    build:
      local:
        push: true
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: your-image-registry/met-alerts-cap-pipeline-beam  # add your image registry as prefix here
