name: java-pr-ci-21-met
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "21-met-metalerts-rss-extractor/**"
      
jobs:
  build-21-rss-extractor:
    uses: ./.github/workflows/java-maven-skaffold-build.yml
    with:
      repositoryFolder: "./21-met-metalerts-rss-extractor/" 