name: java-pr-ci-22-met
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "22-met-alerts-cap-extractor/**"
      
jobs:
  build-22-cap-extractor:
    uses: ./.github/workflows/java-maven-skaffold-build.yml
    with:
      repositoryFolder: "./22-met-alerts-cap-extractor/" 