# Builds the container and pushes to the Google Artifact Registry
name: java-maven-skaffold-build-push-gcr
on:
  workflow_call:
    inputs:
      repositoryFolder: 
        description: "The code repository folder to build. '.' for the root folder, './folder1/mavenRoot/' for a sub-folder"
        default: '.'
        required: false
        type: string
      javaVersion:
        description: 'The Java version to build and deploy. Default is Java17'
        default: '17'
        required: false
        type: string
      imageTag:
        description: "The tag to attach to the container image."
        default: "latest"
        required: false
        type: string
jobs:
  build-push-skaffold-gar:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    #defaults:
    #  run: 
    #    working-directory: ${{ inputs.repositoryFolder }} 
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ inputs.javaVersion }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.javaVersion }}
          distribution: "temurin"
          cache: "maven"
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_CICD_INSO_AKERBP }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1

      - name: Setup artifactory auth
        run: gcloud auth configure-docker europe-docker.pkg.dev # (1)

      - name: Build image with Skaffold
        uses: hiberbee/github-action-skaffold@1.27.0
        with:
          skaffold-version: 2.1.0
          working-directory: ${{ inputs.repositoryFolder }}
          command: build
          push: true
          repository: "europe-docker.pkg.dev/cognite-inso-akerbp/akerbp"
          tag: ${{ inputs.imageTag }}
